usr/share/chronos/chronos.monit, usr/share/clearwater/bin/poll_chronos.sh
Matt, can you review this change to add a poll_chronos script. This uses a generic poll-http script (taken from poll_homestead) that runs in the correct namespace. 
I've tested against a normal Chronos node and a multiple networks one
Fixes #97
=> [Reviewer: Matt] Add poll_chronos script

debian/control, debian/rules
This fixes up debian/control to:
* allow building without google-mock installed, because we now have the submodule
* allow you to install on a 14.04 system, by using Boost 1.54.0 as the dependency, not 1.46.1.
(It's possible to allow you to install on both 12.04 and 14.04 with the syntax `libboost-program-options1.46.1 | libboost-program-options1.54.0`, but that's not a requirement here.)
=> [Reviewer: Ellie] Use 14.04's Boost version as a dependency

src/main/main.cpp
Fixes Metaswitch/sprout#973 (partly)
=> [Reviewer: Andy] Ensure process name passed to openlog() lasts for duration of program

debian/control
Same fix as Metaswitch/homestead#194.
=> [No review required] Chronos depends on libevent-2.0-5

src/main/globals.cpp
Fixes https://github.com/Metaswitch/chronos/issues/126.
Tested by running Chronos with no config files present, with just chronos.conf present and with both chronos.conf and chronos_cluster.conf present. Chronos started up with the correct options in each case.
=> Reviewer AMC: Set defaults if no config files are present

doc/clustering.md
We don't use chronos.conf for clustering any more, right?
Also, service reload chronos isn't a thing afaik, so I've fixed that.
=> Reviewer EM: Update clustering.md

Makefile, doc/api.md, mk/platform.mk, src/include/timer.h, src/include/timer_store.h, src/main/timer.cpp, src/main/timer_store.cpp, src/test/test_timer.cpp, src/test/test_timer_handler.cpp, src/test/test_timer_store.cpp, src/test/timer_helper.cpp
Fixes https://github.com/Metaswitch/chronos/issues/85.
The approach is that Chronos always talks in terms of offsets from the current time (the `start-time-delta` field in the JSON) this means we can translate from the monotonic clock on one Chronos instance to the monotonic clock on another Chronos with no loss of accuracy.
For back compatibility, Chronos also adds `start-time` based on it's local wall clock and handles receiving JSON without `start-time-delta` from old nodes.  Some future version might remove the old API.
=> Reviewer Rob - Monotonic timers

src/include/timer.h, src/main/timer.cpp
Fixes the ToJSON test when the monotonic clock is close to wrapping.
=> No review required - Slice timestamps to uint32_t size

src/main/timer_store.cpp
Fix up valgrind warning about printing a `uint32_t` as a `uint64_t`.
=> No review required - Log the correct-sized variable

Makefile, src/include/chronos_internal_connection.h, src/include/timer_handler.h, src/main/chronos_internal_connection.cpp, src/main/main.cpp, src/main/timer_handler.cpp, src/test/test_chronos_internal_connection.cpp, src/test/test_timer_handler.cpp
In general just replaced existing LVC model with pre-defined SNMP counter tables, and added a Continuous Accumulator Table and a scalar to report the timer count. As timer changes occur within a mutex lock, this is also a safe place to update the count, and report the statistics
=> Reviewer: Matt] - Added stateful statistics and replaced existing LVC model

src/include/timer.h, src/include/timer_store.h, src/main/timer_store.cpp, src/test/coverage-not-yet, src/test/test_timer.cpp, src/test/test_timer_store.cpp
Sorry for all the hideous whitespace updates.
In general, most variables are kept as 64-bit integers, but when comparing or doing calculations with them, we either cast them down to 32, or use the function with takes 32bit integers as parameters
Confirms it passes all unit tests, although added SNMP stats to the "non-covered" list.
=> [Reviewer: Andy] - Fixed overflow errors when comparing

src/include/timer.h, src/include/timer_store.h, src/main/http_callback.cpp, src/main/main.cpp, src/main/timer.cpp, src/main/timer_store.cpp, src/test/test_timer.cpp, src/test/test_timer_handler.cpp, src/test/test_timer_store.cpp
The branch name is now misleading as timers are now stored as 32 bit numbers and overflow is expected and accounted for.
Bucket sizes are now powers of 2 to reduce problems of overflow, when there would be two buckets covering the same time window. The short and long wheel covers nearly the same amount of time as before (1000ms -> 1024ms and 3,600,000ms -> 4,194,304ms)
=> [Reviewer: Andy] - Update bucket size and make timers consistent

src/include/handlers.h, src/main/handlers.cpp, src/test/test_handler.cpp
Andy,
Please can you review?  As discussed, I couldn't find a decent way of UT-ing that timer IDs were "unique", so I checked it by eye and left my code in but commented out.
Fixes #169.
Matt
=> [Reviewer: Andy] Don't truncate unique timer identifiers

debian/chronos.init.d
Andy,
Please can you review my fix to use an internal SNMP community for Chronos' wait-sync operation?
In combination with https://github.com/Metaswitch/clearwater-infrastructure/pull/242, this fixes Metaswitch/chronos#167.  I've tested live.
Matt
=> [Reviewer: Andy] Use internal SNMP community for wait-sync operation

scripts/chronos_resync.py, src/include/timer_store.h, src/main/chronos_internal_connection.cpp, src/main/handlers.cpp, src/main/timer_store.cpp
This catches several locations where we would truncated the 64bit Timer ID.
Also included is an update to resync_test to make tests pass/fail consistently
=> [Reviewer: Ellie] Fix for truncated timer IDs

Makefile, src/include/timer_handler.h, src/main/main.cpp, src/main/timer_handler.cpp, src/test/test_timer_handler.cpp
Shifted table initialisation to below Pidfile lock. Spread the scalar table throughout the files and the tests. Not really much going on here.
=> [Reviewer: Andy] Scalar infinite table

Makefile, src/include/globals.h, src/main/globals.cpp, src/main/main.cpp
I've picked 50ms as the target latency (half of Sprout's), and a 500 req/sec initial request rate (equal to Sprout's rate on a two-core system).
=> [Reviewer: Andy] Add overload control to keep latency below 50ms

src/include/timer_handler.h, src/main/http_callback.cpp, src/main/timer_handler.cpp, src/test/mock_timer_handler.h, src/test/test_timer_handler.cpp
This PR includes the changes made to overcome the issue of leaking statistics. 
The issue was being caused by sprout re-sending a timer PUT update before the chronos callback had completed, and then chronos setting a tombstone over the new timer, meaning it was never deleted properly.
=> [Reviewer: Ellie] Changes to fix callback lockup issue

src/test/coverage-not-yet
Take out cpp-common files from coverage-not-yet
=> [No reviewer] Move cpp-common UTs to cpp-common

chronos.root/usr/share/clearwater/clearwater-cluster-manager/plugins/chronos_plugin.py
It looks like this didn't make it into the original pull request :frowning:. Can you please check it over?
Use alarm_manager from python-common.
=> [Reviewer Ellie] Fix up Chronos plugin to use new alarm infrastructure.

chronos.root/usr/share/chronos/chronos.monit
Use check-uptime to clear alarms and avoid suprious monit failures.
=> [Reviewer: None] Use updated check-uptime script.

chronos.root/usr/share/clearwater/clearwater-cluster-manager/plugins/chronos_plugin.py
This should fix the alarm flicker issue seen in live testing. 
Previously, on_stable_cluster called on_cluster_changing, which set the alarm, before it then cleared the alarm. 
Now the function of write_chronos_cluster_settings has been pulled out of on_cluster_changing so that on_stable_cluster can call it without causing the alarm to flicker.
The same changes have been made in the memcached_plugin.py  https://github.com/Metaswitch/clearwater-infrastructure/pull/300
=> [Reviewer: Rob] Separate write_cluster_settings functionality

chronos.root/usr/share/chronos/chronos.monit, chronos.root/usr/share/clearwater/infrastructure/scripts/check-chronos-uptime
Monit can't pass arguments to check-program scripts in its current version.
=> [Reviewer: None] Cope with Monit restrictions

chronos.root/usr/share/clearwater/clearwater-cluster-manager/plugins/chronos_plugin.py, include/globals.h, include/timer.h, src/globals.cpp, src/timer.cpp
This extracts an instance ID and a deployment ID from ten bits of the UUID. This substantially mitigates https://github.com/Metaswitch/chronos/issues/70 (see the birthday paradox calculations in that issue).
As we discussed, I've made the cluster manager responsible for setting this, as in the long term we'll probably want to use the cluster manager to agree a guaranteed-unique ID.
Tested by spinning up four Sprout nodes and checking they got different values:
```
]$ for i in {1..4}; do ssh sprout-$i.rkd.cw-ngv.com "cat /etc/chronos/chronos_cluster.conf"; done
Warning: Permanently added 'sprout-1.rkd.cw-ngv.com' (ECDSA) to the list of known hosts.
Warning: the ECDSA host key for 'sprout-1.rkd.cw-ngv.com' differs from the key for the IP address '54.175.247.195'
Offending key for IP in …
```
=> [Reviewer: Andy] Ensure uniqueness (kind of)

include/timer_store.h, src/ut/test_timer_replica_choosing.cpp, src/ut/test_timer_store.cpp
The Chronos UTs are slow because we do too much work. I have changed some constants so we do less work. We still get full coverage, and `make full_test` finishes in 1m30s in my test, whereas it's taken 30+ minutes recently on the repo server.
=> [Reviewer: Andy] Faster UTs

include/chronos_internal_connection.h, include/globals.h, include/timer_handler.h, src/chronos_internal_connection.cpp, src/handlers.cpp, src/http_callback.cpp, src/replicator.cpp, src/timer.cpp, src/timer_handler.cpp, src/timer_store.cpp
This fixes up some warnings from running cppcheck (http://cppcheck.sourceforge.net/) over our codebase. (I'm going to send an email round the team on whether we should do this systematically - I like the results.)
In order of importance:
* We were using `replicas.empty()` in one place where we meant `replicas.clear()`
* We weren't catching exceptions by reference (http://stackoverflow.com/questions/8350526/catching-exceptions-by-reference)
* `Globals` and `TimerHandler` had pointer members (so couldn't safely be copy-constructed) but we hadn't explicitly removed the copy constructor
* We used C-style casts instead of (safer and easier to grep for) C++-style casts
* We had some unused variables, and some which could be narrower in scope
* Some constructors weren't initialising all their …
=> [Reviewer: Ellie] Apply cppcheck fixes

src/main.cpp
A similar type of fix to the other PRs - this moves the parsing of global configuration to after the process has daemonised
Fixes #254
=> [Reviewer: Alex] Parse globals after daemonising

include/timer.h, include/timer_store.h, src/Makefile, src/timer.cpp, src/timer_store.cpp, src/ut/test_timer_store.cpp
This switches to the timer heap from https://github.com/Metaswitch/cpp-common/pull/517, which fixes #257, #258 and #259.
One question I'd particularly like your view on: I've made the heap store a `Timer*` (the active timer) rather than a TimerPair. is this right? I didn't quite understand the connection between active and information timers - I think if a timer's in the store it's always an active timer, and information timers are just how we track timers that have been resynced away, but I wasn't sure.
(I previously also asked "I hit a UT issue relating to overflow, where I had timers for 1 hour, 5 hours and 10 hours and the 5-hour one popped first in the Overflow2h case. I fixed this by using a 3-hour timer rather than a 1-hour one. I think this is working as designed - I think any …
=> [Reviewer: Ellie] Move to working timer heap

chronos.root/usr/share/clearwater/clearwater-cluster-manager/plugins/chronos_plugin.py
A rogue comma at the end of a line in chronos_plugin.py broke additions of a sprout node to the chronos cluster.
=> [Reviewer EM] Bad comma invalidates search for 'joining' state

debian/chronos.init.d
Fix to the OID used by chronos wait sync to determine the number of nodes to sync (regression introduced by https://github.com/Metaswitch/cpp-common/pull/527)
=> [Reviewer EM] Incorrect OID for nodes left to query

src/timer_handler.cpp, src/ut/test_timer_handler.cpp
Changed the logic to the if statement for deciding whether to tombstone timers and added a UT.
Fixes https://github.com/Metaswitch/chronos/issues/276
=> [Reviewer: Ellie] Fix issue 276 - timers with interval 0 never get tombstoned

src/timer_handler.cpp
I got confused by this comment in #284 - on reflection, 'replacing' is the wrong word to use here. How's this wording?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/metaswitch/chronos/287)
=> [Reviewer: Ellie] Fix incorrect use of 'replacing' in comment

doc/Development.md, include/chronos_internal_connection.h, include/http_callback.h, src/Makefile, src/chronos_internal_connection.cpp, src/http_callback.cpp, src/main.cpp, src/ut/coverage-not-yet, src/ut/test_http_callback.cpp, src/ut/test_timer_handler.cpp, src/ut/timer_helper.cpp
Ellie,
Please can you review this enhancement to make HttpCallback use HttpClient rather than curl.  This gives us better retry behavior on failure.
This pull request also includes moving the internal connection to use HttpClient, rather than HttpConnection (and it's override_server function) as we think that might be thread-unsafe.
UTs pass, but not live-tested yet.
Matt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/metaswitch/chronos/288)
=> [Reviewer: Ellie] Move from curl and HttpConnection to HttpClient

doc/api.md, include/chronos_internal_connection.h, include/constants.h, include/timer_handler.h, src/chronos_internal_connection.cpp, src/handlers.cpp, src/timer_handler.cpp, src/ut/mock_timer_handler.h, src/ut/test_chronos_internal_connection.cpp, src/ut/test_handler.cpp, src/ut/test_timer_handler.cpp
Add the time-from parameter to resync operations. This isn't used yet, but means that all nodes can accept/send time-from values.
Tested in UT
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/metaswitch/chronos/291)
=> [Reviewer: Rob] Add time-from parameter parsing

src/globals.cpp, src/ut/test_globals.cpp
When parsing the remote site, add the bind port to the URI if there's no port there already
Fixes #298
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/metaswitch/chronos/299)
=> [Reviewer: Sathiyan] Use bind port if there's no port specified

chronos.root/usr/share/clearwater/node_type.d/10_chronos, chronos.root/usr/share/clearwater/node_type.d/90_chronos
Change nodetype so that it only gets picked up if there are no other packages installed that define a higher priority.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/metaswitch/chronos/301)
=> Mgm fix nodetype

include/timer_handler.h, include/timer_store.h, src/chronos_internal_connection.cpp, src/timer_handler.cpp, src/timer_store.cpp, src/ut/test_chronos_internal_connection.cpp, src/ut/test_timer_handler.cpp
This PR
- Removes the overdue iterator as we no longer check for out of date timers.
- Checks if there are multiple timers with the same pop time, and returning all those timers even if we're over the maximum requested number of timers, to avoid getting stuck in a loop
- Fixes the UTs to use the current time rather than 0 when requesting timers. 
Tested live and in UTs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/metaswitch/chronos/308)
=> [Reviewer: Rob] Check for multiple timers

src/chronos_internal_connection.cpp, src/ut/base.cpp, src/ut/test_timer.cpp
Add the default port on deletes if the server doesn't have a default port. 
Tested in UTs - I've changed the default cluster addresses to a mix of with/without ports, and fixed up the UTs to accept this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/metaswitch/chronos/309)
=> [Reviewer: Adam] Use default port on deletes

src/ut/test_chronos_internal_connection.cpp
This means we now need to specify the IPs that a request will be sent to.
Note, in some cases there are multiple requests being sent. This makes the UTs a lot more specific about what we are testing.
I've tested by running the UTs using `make full_test`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/metaswitch/chronos/317)
=> [Reviewer: Ellie] Fix up Chronos UTs now that we don't resolve IPs

include/timer_handler.h, src/timer_handler.cpp, src/ut/test_timer_handler.cpp
When selecting a timer for updating the replica tracker, always choose an
out-of-date active timer in preference to any informational timer.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/metaswitch/chronos/316)
=> [Reviewer: Ellie] Don't update info timer if there's an out of date active timer

src/chronos_internal_connection.cpp, src/timer_handler.cpp, src/ut/test_chronos_internal_connection.cpp, src/ut/test_timer_handler.cpp
Only count a timer if we're going to send it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/metaswitch/chronos/319)
=> [No reviewer] Move retrieve timer increment to the correct place

Makefile, scripts/chronos_fv_test.py, scripts/chronos_pop.py, scripts/chronos_pop_errors.py, src/http_callback.cpp
Fixes issue #312 
Testing done:
- FV test
- Live testing: created 2-sprout deployment, changed sprout on one node to return 503 responses, verified that the Subscription timeout and Registration timeout live tests failed before this fix and passed after
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/metaswitch/chronos/320)
=> [Reviewer: Ellie] Don't treat HTTP error codes on callbacks as success

src/globals.cpp
If we hit an exception trying to parse on of the config files, catch it and try to log a helpful error message to make it easier to diagnose what went wrong, then exit.
(If the problem was with logging config, we can't write a log)
Fixes #266 
Testing done:
- verified the live tests still pass 
- verified we get a helpful log message if there's a problem. The ouput we see is like:
> 24-11-2016 12:51:43.631 UTC Error globals.cpp:155: Error parsing config file: /etc/chronos/chronos.conf
> 24-11-2016 12:51:43.631 UTC Error globals.cpp:156: the argument ('7253A') for option 'port' is invalid
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/metaswitch/chronos/322)
=> [Reviewer: Ellie] More helpful error message if unable to parse config file

src/globals.cpp, src/ut/test_globals.cpp
rather, we should include the local node only if there are no other staying,
joining or leaving nodes
also, use loopback IP not localhost to remove the requirement for a localhost
DNS entry
Fixes #315
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/metaswitch/chronos/324)
=> [Reviewer: Ellie] Staying nodes shouldn't include localhost by default

scripts/chronos_fv_test.py, src/main.cpp
We want to ensure the FV tests use the same ones as would be used by an actual Chronos process installed via debian package.
=> [Reviewer: Ellie] Ensure we're using the correct libs when running the FV tests

include/timer_store.h, src/timer_store.cpp, src/ut/test_timer_store.cpp
This fixes an issue whereby the TSIterator could miss some timers, which meant that not all timers were replicated to the correct nodes when a resync happened.
Chronos stores timers in either the short wheel, the long wheel or the heap. Each wheel is divided into buckets, and all timers in a short wheel bucket pop at once. As time advances, the short wheel is advanced. Once the end of the wheel is reached, all timers from the current bucket in the long wheel are moved into the short wheel, the short wheel starts from the beginning again and the long wheel is advanced. Once the end of the long wheel is reached, timers are moved into the long wheel from the heap and the long wheel starts from the beginning again.
The ISIterator is used to iterate through all timers, in order, from a …
=> [Reviewer: Ellie] Fix Timer iterators

Makefile, include/timer.h, scripts/chronos_delete_timers.py, src/handlers.cpp, src/timer.cpp, src/ut/test_timer.cpp, src/ut/test_timer_store.cpp
This PR fixes an issue where a tombstone doesn't have any site/replica information, and so wasn't being replicated within/across sites.
Tested live and in UTs, `make full_test` and `make fv_test` pass
=> [Reviewer: Seb] Add replica and site info to tombstones

src/main.cpp
The previous fix broke timers because we decide the address family based on the bind address so we always chose IPv6. The fix is to use the local IP like sprout does. This should be IPv4/6 address depending on what the user wants so we should create the right sort of HTTP resolver.
Tested that the live tests pass now.
=> [Reviewer: RJW2] Decide address family from local IP

src/main.cpp
Hi Ellie
Can you sign off on the tweak to the DnsCachedResolver constructor for my DNS timeout enhancement?  I decided to stick with the regular default (rather than the anomalous 1 second override we discussed) in the interests of simplicity.
=> [Reviewer EM] Tweak DNS cached resolver constructor parameters

src/globals.cpp, src/main.cpp, src/ut/test_globals.cpp
Now that we expect chronos.conf to be set up at start of day, it's safe to derive the address family from the bind address. I've gone back to defaulting to using an IPv4 bind address so that chef deployments still work.
=> [Reviewer: EM] Decide address scheme from bind address

doc/configuration.md, include/globals.h, src/globals.cpp, src/timer.cpp, src/ut/base.cpp, src/ut/chronos_shared.conf, src/ut/chronos_unknown_options.conf, src/ut/test_globals.cpp, src/ut/test_handler.cpp, src/ut/test_timer.cpp, src/ut/test_timer_replica_choosing.cpp
This removes the timers:id-format and the alarms:enabled options from Chronos. I've also made it so that we ignore unknown options in the config files, to cope with any backwards compatibility issues.
Tested in UTs and FVs.
=> [Reviewer: Sathiyan] Remove dead code

doc/configuration.md, include/globals.h, include/gr_replicator.h, src/globals.cpp, src/gr_replicator.cpp, src/main.cpp, src/ut/chronos.conf, src/ut/mock_gr_replicator.h, src/ut/test_globals.cpp, src/ut/test_gr_replicator.cpp
This PR makes the number of GR threads a config option rather than defaulting to 20. I had set the number of GR threads to be large, but I think it's better to keep it a low number by default - what do you think?
Tested in UTs/FVs only.
=> [Reviewer: Sathiyan] Make number of GR threads configurable

debian/chronos.init.d
Hi Ellie
This is the change to increase the file handle limit to 10,000 to head off any future FH-related terminations that we discussed a few days back.  This should allow order of 10 FHs to be opened per chronos thread before we hit terminations.
I've checked that this setting addresses the terminations we were seeing on the fielded v10 system.
=> [Reviewer EM] Raise file handle headroom to 10-20 per thread

include/http_callback.h, include/replicator.h, src/Makefile, src/http_callback.cpp, src/main.cpp, src/replicator.cpp, src/ut/coverage-not-yet, src/ut/mock_replicator.h, src/ut/test_http_callback.cpp, src/ut/test_replicator.cpp
Moves us over to using the httpclient in all Chronos, which is good.
I've also added the exception handler to the http_callback code.
There's a couple of things marked as TODO in my changes, which are obviously not the final thing. The first one is about send_post in http_callback, where i think we just need to re-work the httpclient to get done nively, so i'm tracking that elsewhere, and will probably just remove the comment. 
The second i'd like to chat about once you've had a look, as i don't really understand why it isn't 'just working'.
Also, Replicator is now fully UT covered :champagne:
=> [Reviewer: Ellie] Replicator uses HTTPClient

debian/chronos.logrotate, include/globals.h, src/globals.cpp, src/main.cpp
Make the corresponding changes from Metaswitch/sprout#2025 to chronos.
I needed to make a few more changes to get this to work with chronos since it has a different config model:
- Chronos needs to call `daemonize()` before creating `__globals` to hold the configuration since globals creates an updater thread, and we can't do that before daemonizing. I need the config in hand to know Chronos's logging direcroty so I've called `freopen` manually after `__globals` is set up to redirect stderr to `chronos_err.log`
- I added a logrotate file for `chronos_err.log`.
Tested by sending signal 11 into chronos and checking that stuff gets written to `chronos_err.log`.
=> [Reviewer: AJH] Log basic stack trace unless aborting

src/main.cpp
As raised in https://github.com/Metaswitch/chronos/pull/367#discussion_r153578364 , chronos shouldn't really have multiple replicators. We didn't want to make the change at that time in case it was destabilising, but should be good to go now. 
We still pass full_test and fv_test. For live testing i used Rob's script as from https://github.com/Metaswitch/clearwater-issues/issues/2375#issuecomment-349085546, and modified it to send in 1 million timers. Pointed it at one vellum in a 2 vellum deployment in EC2, and all seems to be working as expected. Timers are popping on both nodes, and Chronos isn't dead.
=> [Reviewer: Ellie] Merge handler_replicator and controller_replicator into one

src/chronos_gr_connection.cpp, src/chronos_internal_connection.cpp
This change makes chronos establish HTTP connections from its HTTP bind address. This is needed to allow clearwater-fv-test to test realistic network conditions such as latency and net splits. 
Tested by running the chronos FV tests and checking with wireshark that the connections were being established from the correct addresses.
=> Establish chronos HTTP connections from the bind address

include/replicator.h, src/replicator.cpp
This is the same change as https://github.com/Metaswitch/chronos/pull/373, but applied to the secret 3rd HTTP client that uses. 
I've tested that this works by running the FV tests.
=> Do replication requests from the HTTP bind address

doc/configuration.md, include/globals.h, src/globals.cpp, src/main.cpp, src/ut/chronos_shared.conf, src/ut/test_globals.cpp
This PR enhances chronos so that you can specify what DNS port to use. This is needed so that the FV tests can run their own DNS server on a non-default port.
I've tested this by:
* Running chronos in the FV tests and confirming that DNS queries were working (by checking the logs). 
* Running the chronos UTs.
=> Make chronos DNS port configurable

include/http_callback.h, src/http_callback.cpp
Despite https://github.com/Metaswitch/chronos/pull/373 and https://github.com/Metaswitch/chronos/pull/374 I managed to miss one of Chronos's HTTP clients. This fixes up the last one to use the bind address when establishing connections. 
I've done a grep to confirm that this is the last HTTP client that chronos has. 
I've also checked that the chronos UTs and FVs still pass.
=> Make the HTTP callback send from the chronos bind address

include/handlers.h, src/handlers.cpp, src/ut/test_handler.cpp
Two years ago we removed the old way of resyncing (which used the url /timers/references) - see the commit [here](https://github.com/Metaswitch/chronos/commit/8ef81088fc5f80120d0c12998257cac61149b492). This PR removes the code that was present to keep backwards compatibility, as this function was removed long enough ago this code is no longer needed.
This also removes the code accepting timers with the old timer ID form, as these haven't been used for around 2 years either - see [here](https://github.com/Metaswitch/chronos/commit/cbb1a4d950749b6343f20b2d38aacf985f53bd25), so this code is also no longer needed.
`make test`, `make full_test` and `make fv_test` still all pass.
=> Remove deprecated code

include/timer.h, src/handlers.cpp, src/ut/test_handler.cpp
In the future we may want to extend the URLs on our PUT/DELETE requests.
This PR changes the way we parse this URL to accept URLs that contain content that isn't understood by chronos. This extra content will be ignored, and the request will still be accepted.
This means a two-step upgrade won't be required in the future if the URL is changed.
`make test`, `make full_test`, and `make fv_test` all pass.
(My death test change also ended up in here, sorry.)
(I'm aware my comment changes here will clash with PR #380, I'll fix this up when merging.)
=> Accept new timer ids

include/chronos_gr_connection.h, include/chronos_internal_connection.h, src/Makefile, src/chronos_gr_connection.cpp, src/chronos_internal_connection.cpp, src/http_callback.cpp, src/main.cpp, src/replicator.cpp, src/ut/test_chronos_internal_connection.cpp
This updates Chronos to use the new interfaces in cpp-common for HTTP requests.
Changes to:
* `ChronosInternalConnection`
* `HttpCallback`
* `ChronosGRConnection`
* `Replicator`
There were a couple of places where we have HTTP URLs, but the new interface requires it to be presented as a scheme, server and path. So I spilt the URLs using the function from `Utils`.
For ChronosInternalConnection, I noticed that the UTs weren't checking what HTTP methods we were actually making - they just set up some fake curl responses which apply to any HTTP method. This seemed bad, so I decided to take this opportunity to fix them up to actually check for the correct methods.
To do this, I had to change all of the UTs in that file, which is why there are so many changes. A summary of the changes I made …
=> [Reviewer: Adam] Use the new HTTP interface from cpp-common
