Metaswitch/chronos

- usr/share/chronos/chronos.monit
- usr/share/clearwater/bin/poll_chronos.sh
Matt, can you review these changes to the chronos monit file? 
The changes:
* add cpu/memory checks
* stop the poll_chronos script from running if chronos isn't
* add a restart command (that doesn't abort the process)
If you're happy, then I'll make the same set of changes to the other monit files
> [Reviewer: Matt] Monit file changes

- debian/chronos.init.d
Same as https://github.com/Metaswitch/homestead/pull/207
> [Reviewer: Andy] Add service run command to run blocking

- Makefile
- readme.md
- scripts/chronos_resync.py
- scripts/log/.gitignore
Matt, can you please review this test script for the Chronos resynchronization operations
> [Reviewer: Matt] Add in live test script

- scripts/chronos_resync.py
- src/include/globals.h
- src/main/globals.cpp
- src/main/main.cpp
- src/test/base.cpp
Rob, can you review this change to split out the Chronos configuration file into per node information, and cluster information?
> [Reviewer: Rob] Add a new cluster configuration file

- doc/clustering.md
- doc/configuration.md
- etc/chronos/chronos.conf.sample
- usr/share/clearwater/bin/chronos_configuration_split.py
Alex, can you please review this script and doc changes to move from one Chronos configuration file to two.
Tested live
> [Reviewer: Alex] Chronos migration

- usr/share/chronos/chronos.monit
Matt, can you review this fix to add groups to monit processing (part of https://github.com/Metaswitch/clearwater-monit/issues/16). I've tested this live. 
I'll make this change to all the monit files, but I won't send the rest for review.
> [Reviewer: Matt] Add in groups

- debian/chronos.postinst
> [No reviewer] Stop chronos in the postinst

- usr/share/clearwater/bin/chronos_configuration_split.py
Check if the cluster file already exists and bail out if it does
Fixes #135
> [Reviewer: Alex] Check if the file exists

- src/main/chronos_internal_connection.cpp
Rob, can you review this change to actually set the Chronos scaling alarm
Fixes #142
> [Reviewer: Rob] Actually set the alarm

- src/test/test_timer.cpp
> No review required - Also use correct maths in UT

- etc/chronos/chronos.conf.sample
- src/main/globals.cpp
- src/main/main.cpp
Fix to move Chronos to use 0.0.0.0 as the default. 
Fixes #166
> [Reviewer: Rob] Allow 0.0.0.0

- src/include/chronos_pd_definitions.h
Andy,
Please can you review this change to make the ENT logs clear on what their impact on statistics is?
Thanks,
Matt
> [Reviewer: Andy] Update ENT logs to make clear the impact on statistics

- debian/chronos.postinst
- debian/chronos.prerm
- usr/share/clearwater/clearwater-cluster-manager/plugins/chronos_plugin.py
Move Chronos plugin to Chronos (no changes to plugin code) and update debian files
> [Reviewer: Andy] Move chronos plugin to chronos

- debian/control
Remove snmp-handler as Chronos uses the new style stats
> [No reviewer] Remove snmp handler

- usr/share/clearwater/clearwater-diags-monitor/scripts/chronos_diags
Get the cluster configuration in diags dumps
> [Reviewer: Matt] Get cluster info in diags dump

- Makefile
- src/main/globals.cpp
- src/main/main.cpp
- src/test/test_timer_handler.cpp
Just some stuff I noticed while testing Chronos stats changes, of note, Chronos has been being built without optimizations for ages.
> Reviewer Rob - Fix random little things

- Makefile
- scripts/chronos_resync.py
- src/include/timer_store.h
- src/main/globals.cpp
- src/main/http_callback.cpp
- src/main/replicator.cpp
- src/main/timer_handler.cpp
- src/main/timer_store.cpp
- src/test/chronos.conf
- src/test/chronos_cluster.conf
- src/test/coverage-not-yet
- src/test/test_globals.cpp
- src/test/test_handler.cpp
- src/test/test_timer_handler.cpp
- src/test/test_timer_store.cpp
- src/test/timer_helper.cpp
Graeme, can you please review these changes to sort out the TODOs in the Chronos code and fix up the coverage?
Fixes #189 and fixes #177
> [Reviewer: Graeme] Chronos fix up

- usr/share/clearwater/clearwater-cluster-manager/plugins/chronos_plugin.py
Part of https://github.com/Metaswitch/clearwater-etcd/pull/223.
> [No reviewer] Write files atomically, avoid corruption

- usr/share/clearwater/clearwater-cluster-manager/plugins/chronos_plugin.py
Let's try again, but unlike https://github.com/Metaswitch/chronos/pull/198, let's merge to dev not master...
> [No reviewer] Fix typo in #196

- src/test/test_timer_handler.cpp
- src/test/timer_helper.cpp
Fix time in chronos tests to avoid race condition and memory leak
> [No Reviewer] UT fixes

- doc/Development.md
> Reviewer Rob - Discuss `make submodules` in the developer docs

- doc/configuration.md
- src/include/globals.h
- src/include/handlers.h
- src/include/timer.h
- src/main/chronos_internal_connection.cpp
- src/main/globals.cpp
- src/main/handlers.cpp
- src/main/timer.cpp
- src/test/base.cpp
- src/test/chronos.conf
- src/test/test_globals.cpp
- src/test/test_handler.cpp
- src/test/test_timer.cpp
- src/test/test_timer_replica_choosing.cpp
- src/test/test_timer_store.cpp
Graeme, can you review this change to allow upgrade to the new timer ID format
Tested live and in UTs
> [Reviewer: Graeme] Support both formats of timer ID to allow seamless upgrade

- debian/chronos.postinst
- debian/chronos.triggers
Add alarm agent triggers - part of fix for https://github.com/Metaswitch/clearwater-snmp-handlers/issues/118
> [No reviewer] Add alarm triggers

- src/ut/coverage-not-yet
Note to self: figure out how to get code coverage working with clang, so I find these errors before Jenkins does.
> [No reviewer] Fix up coverage paths

- src/main.cpp
> [Reviewer: Rob] Clear scale up alarm at startup. Remove clear-all call

- chronos.root/usr/share/clearwater/clearwater-cluster-manager/plugins/chronos_plugin.py
Hopefully these are the sort of changes you were envisioning. 
If so, i'll do the same for the cassandra and memcached plugins, and ensure the queue manager is similar.
> [Reviewer: Rob] Etcd plugin alarm changes

- src/globals.cpp
Moving https://github.com/Metaswitch/chronos/pull/252 to be against release-94-fixes
> [No Reviewer] Change max_tokens default to 100

- debian/chronos.init.d
- src/main.cpp
Following the change in https://github.com/Metaswitch/cpp-common/pull/505
> [No reviewer] Use new signal handler start

- .gitignore
- doc/Development.md
- rpm/chronos.spec
These changes document how to build the Chronos package (note that things like the zmq install should really change, but I wanted to get the current process written up)
> [Reviewer: Alex] Centos doc changes

- src/main.cpp
Using the new AlarmManager from https://github.com/Metaswitch/cpp-common/pull/526
> Use the new AlarmManager

- src/timer_handler.cpp
> [Reviewer: Graeme] Fix up coverage loss

- src/globals.cpp
- src/ut/chronos_gr.conf
- src/ut/test_globals.cpp
Ignore the local site if it's specified in the remote sites
> [No reviewer] Add local site removal from remote sites

- src/Makefile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/metaswitch/chronos/286)
> Add HttpConnectionPool class to Makefile

- src/chronos_internal_connection.cpp
- src/timer.cpp
- src/ut/test_timer.cpp
This fixes issue #282 by using the new bracketing functions introduced in https://github.com/Metaswitch/cpp-common/pull/555
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/metaswitch/chronos/289)
> [Reviewer: RKD] Correctly handle IPv6 addresses

- include/timer.h
- include/timer_handler.h
- include/timer_store.h
- src/handlers.cpp
- src/timer.cpp
- src/timer_handler.cpp
- src/timer_store.cpp
- src/ut/mock_timer_handler.h
- src/ut/mock_timer_store.h
- src/ut/test_handler.cpp
- src/ut/test_timer_handler.cpp
- src/ut/test_timer_store.cpp
- src/ut/timer_helper.cpp
Remove info timers. I've split this PR out from the rest of the code as otherwise it's too hard to see what changes I've made.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/metaswitch/chronos/292)
> [Reviewer: Rob] Remove informational timers

- debian/chronos.install
- debian/chronos.postinst
- debian/control
Install the new Chronos config plugins/scripts from https://github.com/Metaswitch/clearwater-etcd-plugins/pull/8
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/metaswitch/chronos/290)
> [Reviewer: Richard] Install chronos config plugins

- src/Makefile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/metaswitch/chronos/295)
> [No reviewer] Fix Makefile after renaming httpresolver.cpp

- chronos.root/usr/share/clearwater/node_type.d/10_chronos
- debian/chronos.init.d
- src/main.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/metaswitch/chronos/297)
> [Reviewer: RKD] Docker split-storage

- src/main.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/metaswitch/chronos/302)
> [No review required] Use new HTTP stack function calls

- chronos.root/usr/share/clearwater/infrastructure/scripts/reload/dns_config/chronos_reload
- debian/chronos.init.d
- src/Makefile
- src/gr_replicator.cpp
- src/main.cpp
Makes use of the changes in https://github.com/Metaswitch/cpp-common/pull/573
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/metaswitch/chronos/303)
> [Reviewer: Ellie] Use static DNS records from dns_config

- include/chronos_internal_connection.h
- include/timer_handler.h
- src/chronos_internal_connection.cpp
- src/handlers.cpp
- src/timer_handler.cpp
- src/ut/mock_timer_handler.h
- src/ut/test_chronos_internal_connection.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/metaswitch/chronos/304)
> [No reviewer] Use uint32_t consistently

- doc/configuration.md
dns_config needs to be set up for GR Chronos
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/metaswitch/chronos/306)
> [Reviewer: Ellie] Docs for dns_config

- include/chronos_pd_definitions.h
- src/Makefile
- src/globals.cpp
- src/main.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/metaswitch/chronos/310)
> Reviewed: Use real syslog

- src/globals.cpp
- src/main.cpp
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/metaswitch/chronos/311)
> No reviewer: Move memory leak to main

- src/chronos_internal_connection.cpp
- src/ut/test_chronos_internal_connection.cpp
Fix resync issue
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/metaswitch/chronos/318)
> [No reviewer] Query the local node for timers as well

- src/ut/test_chronos_internal_connection.cpp
Fix UTs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/metaswitch/chronos/321)
> [No reviewer] Fix UTs after IP resolve changes

- Makefile
- debian/control
- scripts/chronos_fv_test.py
- scripts/chronos_pop_errors.py
- src/chronos_internal_connection.cpp
- src/globals.cpp
- src/timer_handler.cpp
- src/ut/base.cpp
- src/ut/test_chronos_internal_connection.cpp
- src/ut/test_gr_replicator.cpp
- src/ut/test_http_callback.cpp
- src/ut/test_timer.cpp
- src/ut/test_timer_handler.cpp
This commit is a merge of dev into the split-clusters branch, which had a bunch of conflicts. I've had to change some of the unit tests to get them to pass, so would like those to be reviewed to check the conflicts were resolved correctly.
Obviously most of these changes have been reviewed already, so the notable conflicts which I'd like reviewed are:
- globals.cpp
- test_gr_replicator.cpp
- test_http_callback.cpp
**Testing**
- UTs pass
- FV tests pass
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/metaswitch/chronos/323)
> [Reviewer: Ellie] Merge dev to split clusters

- Makefile
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/metaswitch/chronos/325)
> [No reviewer] Allow major version to be overridden

- debian/chronos.init.d
Equivalent PR to https://github.com/Metaswitch/astaire/pull/77 for chronos
> [Reviewer EM] Cap sync waits at 10 minutes so that scaling can complete

- doc/clustering.md
Add in the `[identity]` section to the cluster doc
> [No reviewer] Add identity documentation

- src/globals.cpp
Fixes Metaswitch/clearwater-issues#2113
Checked this worked by upgrading my chef deployment.
> [Reviewer: RJW2] Bind to the IPv6 any address

- debian/chronos.links
I also found some missing links.
> [Reviewer: EM] Add shortcuts to chronos scripts

- chronos.root/usr/share/chronos/chronos.monit
As per https://github.com/Metaswitch/sprout/pull/1863
> [No reviewer] Don't wait for 6 cycles before killing a process

- chronos.root/etc/chronos/chronos.conf.sample
- debian/chronos.install
- debian/chronos.links
- doc/api.md
- doc/configuration.md
- include/globals.h
- scripts/chronos_fv_test.py
- scripts/chronos_gr.py
- src/globals.cpp
- src/main.cpp
- src/ut/base.cpp
- src/ut/chronos_gr.conf
- src/ut/chronos_local_override.conf
- src/ut/chronos_shared.conf
- src/ut/test_globals.cpp
This PR renames the GR config file to a shared config file, moves the shared configuration from the local config file to the new shared config file, and adds a new DNS timeout parameter.
> [Reviewer: Krista] Rename Chronos file

- include/timer.h
> [No reviewer] Remove unused definition

- src/chronos_gr_connection.cpp
Follow on from Metaswitch/cpp-common#666.
> [Reviewer: EM] Create ChronosGRConnection with a remote HttpConnection

- chronos.root/usr/share/clearwater/infrastructure/alarms/chronos_alarms.json
- include/chronos_gr_connection.h
- include/gr_replicator.h
- src/Makefile
- src/chronos_gr_connection.cpp
- src/gr_replicator.cpp
- src/main.cpp
- src/ut/test_gr_replicator.cpp
Adds an alarm for when all remote chronos connections are down.
> [Reviewer: EM] Add alarm for remote chronos connection failure

- chronos.root/usr/share/chronos/chronos.monit
- chronos.root/usr/share/clearwater/bin/poll_chronos.sh
- chronos.root/usr/share/clearwater/infrastructure/monit_stability/chronos-stability
Process-specific changes for [#522](https://github.com/Metaswitch/clearwater-infrastructure/pull/522). Worth comparing to [#2024](https://github.com/Metaswitch/sprout/pull/2024).
> [Reviewer: KH1] Improve Monit polling behavior during monitored process restart

- chronos.root/usr/share/clearwater/bin/poll_chronos.sh
https://github.com/Metaswitch/cpp-common/pull/744
Created Chef deployment and monit summary check that Chronos is running fine
> Chronos listen on public address
